### ISSUE TITLE
Can't get certificate to work (Linux)

### ISSUE THREAD

**Issue by j-panasiuk** [mike-north/pwa-fundamentals#27]
Hi! First of all, thanks for taking the effort to prepare this course! This is something that I've been looking for and it's great to have both high-level overview of PWAs and practical examples gathered and explained in one place :)

Unfortunately I'm currently stuck trying to get HTTPS certificate to work.
I think I screwed something up during the installation.
I was just going along the instructions in README and ran
```
npm run prepcerts
```
At that point I didn't expect that popup in Firefox asking for some permissions, so I decided to skip them for the time being (left all the checkboxes unchecked) and come back and change them later.

Later I checked that I had **devcert** Authority under "Certifiacates / Authorities" tab, but all the browsers considered the page "Not secure". So, apart from silly warnings, I was also unable to run Lighthouse tests.

Finally I tried to do fresh reinstall - I cloned the repository, deleted **devcert** authority from Firefox settings and tried to generate the certifacte again. Unfortunately, it seems that I can generate local keys, but I can't get the Firefox prompt to show up and create the certifiacte for me.

I check devcert README (https://github.com/davewasmer/devcert#how-it-works) and what I found is:

> When you ask for a development certificate, devcert will first check to see if it has run on this machine before. If not, it will create a root certificate authority and add it to your OS and various browser trust stores. You'll likely see password prompts from your OS at this point to authorize the new root CA. This is the only time you'll see these prompts.

How should I proceed to get this certificate if I've already run it once on my machine?

**Comment by mike-north** [comment]
Hi @j-panasiuk,

This is one of the sharp edges I hoped to smooth out a little better in the dev tools. Here are some things you can try.

The certificates in question are probably in `~/.config/devcert`. Make sure you've trusted both
* `~/.config/devcert/devcert-ca-root.crt` <-- the devcert root certificate
* `~/.config/devcert/frontend-grocer.crt` <-- the leaf-level certificate, signed by the devcert root

How you trust a cert varies depending on linux distribution, but [this stackexchange answer](https://unix.stackexchange.com/a/90607) seems to cover a few bases.

If you figure this out, please post the steps you took here so that other users may benefit. If all else fails, you can try [telling chrome to ignore TLS errors on localhost](https://improveandrepeat.com/2016/09/allowing-self-signed-certificates-on-localhost-with-chrome-and-firefox/), but I've found a few cases where errors are NOT ignored in some versions of chrome.

**Comment by j-panasiuk** [comment]
Thanks for the hints! After a bit of fiddling with suggestions presented in [stackexchange answer](https://unix.stackexchange.com/a/90607) I persuaded both Firefox and Chrome to accept the certificates

For the record, in my case it's Linux Mint 18 (it should probably work similarly under Ubuntu).
If you are running into a similar problem, my suggestions would be:

1) Make sure you have `devcert` listed as Certificate Authority (CA) in your browser settings
For Chrome you can find those under **Settings** > _(show advanced settings)_ > **HTTPS/SSL** > Manage certificates > Authorities

2) Use **Edit** on `devcert` to make sure you have all 3 options checked

Steps 1-2 work are pretty much identical for Firefox.
If at this point the browsers are still treating the certificates as invalid

3) Look if the following certificates have been generated:
`~/.config/devcert/devcert-ca-root.crt`
`~/.config/devcert/frontend-grocer.crt`
Then you can try to [copy these certificates](https://superuser.com/questions/437330/how-do-you-add-a-certificate-authority-ca-to-ubuntu#answer-437377) into `/usr/local/share/ca-certificates` directory and follow it up with running `(sudo) update-ca-certificates`.

In my case result of the update was
```
...
2 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

Adding debian:devcert-ca-root.pem
Adding debian:frontend-grocer.pem
```
which solved the problem
